### ISSUE TITLE
파일 입출력

### ISSUE THREAD

**Issue by KeumYoungHwan** [ManaBob/ManaBob#12]
파일 입출력 함수, class 여러가지 다 찾아봤는데
File 
System.Environment.Get 어쩌고 path받아오는 것도 안되고
시간 대비 너무 한게 없네요

**Comment by luncliff** [comment]
코멘트가 늦었네요. 괜찮습니다. 확인해보니 일반적인 C# 어플리케이션처럼 File 처리를 하는게 어려운 것 같습니다. (Store 같은 곳을 통해서 다운로드 받기 때문에 그런 것인지도...) 

`LocalService`쪽은 대안을 찾은 뒤에 이 Issue를 다시 열도록 하겠습니다.
