### ISSUE TITLE
Server 모델 의견 제안

### ISSUE THREAD

**Issue by luncliff** [ManaBob/ManaBob#3]
이번 스프린트에는 간단한 수준(Echo)의 JSON 통신을 하는 것을 생각하고 있습니다.
@lilynys 님 의견을 듣고 싶습니다. 어떤, 어느정도의 작업이 필요할까요?

**Comment by yetree** [comment]
주말 동안 python을 이용하여 서버 구현을 해보려 했으나 참고 자료가 미비하여 json + socket.io로 구현하기로 결정하였습니다. 기본적인 채팅은 이번주 금요일 내로 마치려고 합니다

**Comment by luncliff** [comment]
@lilynys 알겠습니다. 그동안 저는 UI 작업에 집중하겠습니다. 따로 제가 신경써야 할 일이 있으면 말씀 부탁드려요.
